package com.raaspal.robotrecommendation.robot.dto;

import com.raaspal.robotrecommendation.robot.entity.RobotSpec;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

public record RobotSpecResponse(
        UUID id,
        UUID robotId,
        Integer lengthMm,
        Integer widthMm,
        Integer heightMm,
        BigDecimal robotWeightKg,
        Integer widthCleaningMm,
        BigDecimal brushPressureKg,
        BigDecimal vacuumPressureKpa,
        BigDecimal speedMs,
        BigDecimal noiseLevelDb,
        Boolean workStation,
        Boolean dockCharge,
        Boolean manualCharge,
        Integer cleaningEfficiencySweepSqmH,
        Integer cleaningEfficiencyScrubSqmH,
        Integer cleaningEfficiencyMopSqmH,
        Integer cleaningEfficiencySweepScrubSqmH,
        Integer cleaningEfficiencyVacuumSqmH,
        BigDecimal tankCapacityCleanL,
        BigDecimal tankCapacityWasteL,
        BigDecimal tankCapacityTrashL,
        BigDecimal tankCapacityDustBagL,
        Boolean cleaningFunctionSweepNoVacuum,
        Boolean cleaningFunctionSweepVacuum,
        Boolean cleaningFunctionMopDry,
        Boolean cleaningFunctionMopWet,
        Boolean cleaningFunctionScrubBrushRoller,
        Boolean cleaningFunctionScrubBrushDisc,
        Boolean navigationLidar2d,
        Boolean navigationLidar3d,
        Boolean navigationCameraVslam,
        String batteryType,
        BigDecimal batteryVoltageV,
        BigDecimal batteryCapacityAh,
        BigDecimal batteryChargingTimeHr,
        BigDecimal batteryWorkTimeSweepHr,
        BigDecimal batteryWorkTimeScrubHr,
        BigDecimal batteryWorkTimeSweepVacuumHr,
        Integer minimumPassableWidthMm,
        Integer minimumPassableHeightMm,
        Integer maximumNarrowCrossMm,
        Integer minimumTurnWidthMm,
        Integer minimumEdgeFromWallMm,
        Integer maximumStepHeightMm,
        BigDecimal slopeAngleDeg,
        Boolean spotAi,
        String outdoorIndoor,
        String ipRating,
        Boolean hepa,
        Boolean floorTypePavingBlocks,
        Boolean floorTypeGranite,
        Boolean floorTypeMarble,
        Boolean floorTypeTerrazzo,
        Boolean floorTypeTerracotta,
        Boolean floorTypeCeramic,
        Boolean floorTypeSmoothConcrete,
        Boolean floorTypeCoarseConcrete,
        Boolean floorTypeStampedConcrete,
        Boolean floorTypeAsphalt,
        Boolean floorTypeEpoxy,
        Boolean floorTypeTile,
        Boolean floorTypeShortCarpet,
        Boolean floorTypeLongCarpet,
        Boolean floorTypeSpc,
        Boolean floorTypeLaminate,
        Boolean floorTypeVinyl,
        Boolean floorLayout2x2,
        Boolean floorLayout4x4,
        Boolean floorLayout8x8,
        Boolean floorLayout10x10,
        Boolean floorLayout12x12,
        Boolean floorLayout20x20,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
) {
    public static RobotSpecResponse from(RobotSpec spec) {
        UUID robotId = spec.getRobot() == null ? null : spec.getRobot().getId();

        return new RobotSpecResponse(
                spec.getId(),
                robotId,
                spec.getLengthMm(),
                spec.getWidthMm(),
                spec.getHeightMm(),
                spec.getRobotWeightKg(),
                spec.getWidthCleaningMm(),
                spec.getBrushPressureKg(),
                spec.getVacuumPressureKpa(),
                spec.getSpeedMs(),
                spec.getNoiseLevelDb(),
                spec.getWorkStation(),
                spec.getDockCharge(),
                spec.getManualCharge(),
                spec.getCleaningEfficiencySweepSqmH(),
                spec.getCleaningEfficiencyScrubSqmH(),
                spec.getCleaningEfficiencyMopSqmH(),
                spec.getCleaningEfficiencySweepScrubSqmH(),
                spec.getCleaningEfficiencyVacuumSqmH(),
                spec.getTankCapacityCleanL(),
                spec.getTankCapacityWasteL(),
                spec.getTankCapacityTrashL(),
                spec.getTankCapacityDustBagL(),
                spec.getCleaningFunctionSweepNoVacuum(),
                spec.getCleaningFunctionSweepVacuum(),
                spec.getCleaningFunctionMopDry(),
                spec.getCleaningFunctionMopWet(),
                spec.getCleaningFunctionScrubBrushRoller(),
                spec.getCleaningFunctionScrubBrushDisc(),
                spec.getNavigationLidar2d(),
                spec.getNavigationLidar3d(),
                spec.getNavigationCameraVslam(),
                spec.getBatteryType(),
                spec.getBatteryVoltageV(),
                spec.getBatteryCapacityAh(),
                spec.getBatteryChargingTimeHr(),
                spec.getBatteryWorkTimeSweepHr(),
                spec.getBatteryWorkTimeScrubHr(),
                spec.getBatteryWorkTimeSweepVacuumHr(),
                spec.getMinimumPassableWidthMm(),
                spec.getMinimumPassableHeightMm(),
                spec.getMaximumNarrowCrossMm(),
                spec.getMinimumTurnWidthMm(),
                spec.getMinimumEdgeFromWallMm(),
                spec.getMaximumStepHeightMm(),
                spec.getSlopeAngleDeg(),
                spec.getSpotAi(),
                spec.getOutdoorIndoor(),
                spec.getIpRating(),
                spec.getHepa(),
                spec.getFloorTypePavingBlocks(),
                spec.getFloorTypeGranite(),
                spec.getFloorTypeMarble(),
                spec.getFloorTypeTerrazzo(),
                spec.getFloorTypeTerracotta(),
                spec.getFloorTypeCeramic(),
                spec.getFloorTypeSmoothConcrete(),
                spec.getFloorTypeCoarseConcrete(),
                spec.getFloorTypeStampedConcrete(),
                spec.getFloorTypeAsphalt(),
                spec.getFloorTypeEpoxy(),
                spec.getFloorTypeTile(),
                spec.getFloorTypeShortCarpet(),
                spec.getFloorTypeLongCarpet(),
                spec.getFloorTypeSpc(),
                spec.getFloorTypeLaminate(),
                spec.getFloorTypeVinyl(),
                spec.getFloorLayout2x2(),
                spec.getFloorLayout4x4(),
                spec.getFloorLayout8x8(),
                spec.getFloorLayout10x10(),
                spec.getFloorLayout12x12(),
                spec.getFloorLayout20x20(),
                spec.getCreatedAt(),
                spec.getUpdatedAt()
        );
    }
}
