package com.raaspal.robotrecommendation.robot.dto;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.PositiveOrZero;

import java.math.BigDecimal;

public record RobotSpecRequest(
        @Positive Integer lengthMm,
        @Positive Integer widthMm,
        @Positive Integer heightMm,
        @Positive BigDecimal robotWeightKg,
        @Positive Integer widthCleaningMm,
        @PositiveOrZero BigDecimal brushPressureKg,
        @PositiveOrZero BigDecimal vacuumPressureKpa,
        @PositiveOrZero BigDecimal speedMs,
        @PositiveOrZero BigDecimal noiseLevelDb,
        Boolean workStation,
        Boolean dockCharge,
        Boolean manualCharge,
        @PositiveOrZero Integer cleaningEfficiencySweepSqmH,
        @PositiveOrZero Integer cleaningEfficiencyScrubSqmH,
        @PositiveOrZero Integer cleaningEfficiencyMopSqmH,
        @PositiveOrZero Integer cleaningEfficiencySweepScrubSqmH,
        @PositiveOrZero Integer cleaningEfficiencyVacuumSqmH,
        @PositiveOrZero BigDecimal tankCapacityCleanL,
        @PositiveOrZero BigDecimal tankCapacityWasteL,
        @PositiveOrZero BigDecimal tankCapacityTrashL,
        @PositiveOrZero BigDecimal tankCapacityDustBagL,
        Boolean cleaningFunctionSweepNoVacuum,
        Boolean cleaningFunctionSweepVacuum,
        Boolean cleaningFunctionMopDry,
        Boolean cleaningFunctionMopWet,
        Boolean cleaningFunctionScrubBrushRoller,
        Boolean cleaningFunctionScrubBrushDisc,
        Boolean navigationLidar2d,
        Boolean navigationLidar3d,
        Boolean navigationCameraVslam,
        String batteryType,
        @PositiveOrZero BigDecimal batteryVoltageV,
        @PositiveOrZero BigDecimal batteryCapacityAh,
        @PositiveOrZero BigDecimal batteryChargingTimeHr,
        @PositiveOrZero BigDecimal batteryWorkTimeSweepHr,
        @PositiveOrZero BigDecimal batteryWorkTimeScrubHr,
        @PositiveOrZero BigDecimal batteryWorkTimeSweepVacuumHr,
        @Positive Integer minimumPassableWidthMm,
        @Positive Integer minimumPassableHeightMm,
        @Positive Integer maximumNarrowCrossMm,
        @Positive Integer minimumTurnWidthMm,
        @PositiveOrZero Integer minimumEdgeFromWallMm,
        @PositiveOrZero Integer maximumStepHeightMm,
        @DecimalMin("0.0") BigDecimal slopeAngleDeg,
        Boolean spotAi,
        String outdoorIndoor,
        String ipRating,
        Boolean hepa,
        Boolean floorTypePavingBlocks,
        Boolean floorTypeGranite,
        Boolean floorTypeMarble,
        Boolean floorTypeTerrazzo,
        Boolean floorTypeTerracotta,
        Boolean floorTypeCeramic,
        Boolean floorTypeSmoothConcrete,
        Boolean floorTypeCoarseConcrete,
        Boolean floorTypeStampedConcrete,
        Boolean floorTypeAsphalt,
        Boolean floorTypeEpoxy,
        Boolean floorTypeTile,
        Boolean floorTypeShortCarpet,
        Boolean floorTypeLongCarpet,
        Boolean floorTypeSpc,
        Boolean floorTypeLaminate,
        Boolean floorTypeVinyl,
        Boolean floorLayout2x2,
        Boolean floorLayout4x4,
        Boolean floorLayout8x8,
        Boolean floorLayout10x10,
        Boolean floorLayout12x12,
        Boolean floorLayout20x20
) {
}
