-- Gausium cleaning-robot catalogue + specs, generated from
-- raaspal-rims/docs/DataSheetGS_filled_07152026.xlsx
-- Idempotent: safe to re-run. Brand typo 'Guasium' normalised to 'Gausium'.
-- 'N/A' in the sheet becomes NULL. New models land as DRAFT so
-- RecommendationService (which filters on VERIFIED) will not recommend them.

BEGIN;

-- ── Gausium Mira ─────────────────────────────────────────────
INSERT INTO robots (brand, model, robot_type, test_status)
SELECT 'Gausium', 'Mira', 'CLEANING', 'DRAFT'
WHERE NOT EXISTS (SELECT 1 FROM robots
                  WHERE lower(brand) = lower('Gausium') AND lower(model) = lower('Mira'));

INSERT INTO robot_specs_cleaning (robot_id,dimension_l_mm,dimension_w_mm,dimension_h_mm,robot_weight_kg,sweep_width_mm,scrub_width_mm,mop_width_mm,brush_pressure_kg,roller_speed_rpm,brush_speed_rpm,vacuum_pressure_kpa,vibration_more_than,noise_level_db,max_travelling_speed_ms,max_operation_speed_ms,sweep_efficiency_sqm_h,scrub_efficiency_sqm_h,mop_efficiency_sqm_h,sweep_scrub_efficiency_sqm_h,vacuum_efficiency_sqm_h,cleaning_capacity_l,waste_capacity_l,trash_capacity_l,dust_bag_capacity_l,dust_bag_charging_dock,auto_clean,max_output_power_w,drive_motor_power_w,battery_type,battery_voltage_v,battery_capacity_ah,battery_charging_time_hr,sweep_work_time_hr,scrub_work_time_hr,mop_work_time_hr,min_pass_width_mm,min_pass_height_mm,max_vertical_obstacle_height_mm,max_trench_clearance_mm,max_narrow_mm,min_u_turn_width_mm,min_edge_from_wall_mm,max_step_height_mm,slope_angle_auto_deg,sensor_distance_m,sensor_degree_deg,ip_rating,hepa,min_operating_temp_c,max_operating_temp_c,min_operating_humidity_pct,max_operating_humidity_pct,application,outdoor,indoor,fn_sweep_no_vacuum,fn_sweep_vacuum,fn_mop_dry,fn_mop_wet,fn_scrub_brush_roller,fn_scrub_brush_disc,nav_2d_lidar,nav_3d_lidar,nav_vslam,sensor_rgb,sensor_rgbd,sensor_ultrasonic,anti_collision,anti_drop,spot_ai,manual_drive,multi_robot_connect,auto_task_switch,iot_integration,work_station,dock_charge,manual_charge,floor_layout_method,floor_rough_surface,floor_smooth_surface,floor_real_wood,floor_paving_blocks,floor_granite_tiles,floor_ceramic_tiles,floor_marble,floor_terrazzo,floor_nature_stone,floor_terracotta,floor_smooth_concrete,floor_coarse_concrete,floor_stamped_concrete,floor_epoxy,floor_pu,floor_asphalt,floor_short_carpet,floor_long_carpet,floor_spc,floor_wpc,floor_laminate,floor_vinyl_pvc,floor_washed_sand)
SELECT r.id,650,550,900,130,750,400,620,25,1000,270,20,NULL,70,1.4,1.4,3780,2016,3124,NULL,NULL,22,20,1.4,NULL,FALSE,TRUE,NULL,204,'Lithium Iron Phosphate',24,60,2,8,4,10,660,950,20,30,NULL,950,0,20,6,NULL,360,'IPX3',NULL,0,40,20,75,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,TRUE,TRUE,FALSE
FROM robots r
WHERE lower(r.brand) = lower('Gausium') AND lower(r.model) = lower('Mira')
  AND NOT EXISTS (SELECT 1 FROM robot_specs_cleaning s WHERE s.robot_id = r.id);

-- ── Gausium Beetle 2.0 ─────────────────────────────────────────────
INSERT INTO robots (brand, model, robot_type, test_status)
SELECT 'Gausium', 'Beetle 2.0', 'CLEANING', 'DRAFT'
WHERE NOT EXISTS (SELECT 1 FROM robots
                  WHERE lower(brand) = lower('Gausium') AND lower(model) = lower('Beetle 2.0'));

INSERT INTO robot_specs_cleaning (robot_id,dimension_l_mm,dimension_w_mm,dimension_h_mm,robot_weight_kg,sweep_width_mm,scrub_width_mm,mop_width_mm,brush_pressure_kg,roller_speed_rpm,brush_speed_rpm,vacuum_pressure_kpa,vibration_more_than,noise_level_db,max_travelling_speed_ms,max_operation_speed_ms,sweep_efficiency_sqm_h,scrub_efficiency_sqm_h,mop_efficiency_sqm_h,sweep_scrub_efficiency_sqm_h,vacuum_efficiency_sqm_h,cleaning_capacity_l,waste_capacity_l,trash_capacity_l,dust_bag_capacity_l,dust_bag_charging_dock,auto_clean,max_output_power_w,drive_motor_power_w,battery_type,battery_voltage_v,battery_capacity_ah,battery_charging_time_hr,sweep_work_time_hr,scrub_work_time_hr,mop_work_time_hr,min_pass_width_mm,min_pass_height_mm,max_vertical_obstacle_height_mm,max_trench_clearance_mm,max_narrow_mm,min_u_turn_width_mm,min_edge_from_wall_mm,max_step_height_mm,slope_angle_auto_deg,sensor_distance_m,sensor_degree_deg,ip_rating,hepa,min_operating_temp_c,max_operating_temp_c,min_operating_humidity_pct,max_operating_humidity_pct,application,outdoor,indoor,fn_sweep_no_vacuum,fn_sweep_vacuum,fn_mop_dry,fn_mop_wet,fn_scrub_brush_roller,fn_scrub_brush_disc,nav_2d_lidar,nav_3d_lidar,nav_vslam,sensor_rgb,sensor_rgbd,sensor_ultrasonic,anti_collision,anti_drop,spot_ai,manual_drive,multi_robot_connect,auto_task_switch,iot_integration,work_station,dock_charge,manual_charge,floor_layout_method,floor_rough_surface,floor_smooth_surface,floor_real_wood,floor_paving_blocks,floor_granite_tiles,floor_ceramic_tiles,floor_marble,floor_terrazzo,floor_nature_stone,floor_terracotta,floor_smooth_concrete,floor_coarse_concrete,floor_stamped_concrete,floor_epoxy,floor_pu,floor_asphalt,floor_short_carpet,floor_long_carpet,floor_spc,floor_wpc,floor_laminate,floor_vinyl_pvc,floor_washed_sand)
SELECT r.id,860,600,550,112,750,NULL,NULL,NULL,NULL,NULL,NULL,NULL,70,1.2,1.2,2000,NULL,NULL,NULL,NULL,NULL,NULL,40,NULL,FALSE,FALSE,NULL,NULL,'Lithium Iron Phosphate',24,60,4,5,10,NULL,1200,NULL,NULL,NULL,NULL,1200,0,NULL,8,70,NULL,'IP54',NULL,NULL,NULL,NULL,NULL,TRUE,TRUE,TRUE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE
FROM robots r
WHERE lower(r.brand) = lower('Gausium') AND lower(r.model) = lower('Beetle 2.0')
  AND NOT EXISTS (SELECT 1 FROM robot_specs_cleaning s WHERE s.robot_id = r.id);

-- ── Gausium Marvel ─────────────────────────────────────────────
INSERT INTO robots (brand, model, robot_type, test_status)
SELECT 'Gausium', 'Marvel', 'CLEANING', 'DRAFT'
WHERE NOT EXISTS (SELECT 1 FROM robots
                  WHERE lower(brand) = lower('Gausium') AND lower(model) = lower('Marvel'));

INSERT INTO robot_specs_cleaning (robot_id,dimension_l_mm,dimension_w_mm,dimension_h_mm,robot_weight_kg,sweep_width_mm,scrub_width_mm,mop_width_mm,brush_pressure_kg,roller_speed_rpm,brush_speed_rpm,vacuum_pressure_kpa,vibration_more_than,noise_level_db,max_travelling_speed_ms,max_operation_speed_ms,sweep_efficiency_sqm_h,scrub_efficiency_sqm_h,mop_efficiency_sqm_h,sweep_scrub_efficiency_sqm_h,vacuum_efficiency_sqm_h,cleaning_capacity_l,waste_capacity_l,trash_capacity_l,dust_bag_capacity_l,dust_bag_charging_dock,auto_clean,max_output_power_w,drive_motor_power_w,battery_type,battery_voltage_v,battery_capacity_ah,battery_charging_time_hr,sweep_work_time_hr,scrub_work_time_hr,mop_work_time_hr,min_pass_width_mm,min_pass_height_mm,max_vertical_obstacle_height_mm,max_trench_clearance_mm,max_narrow_mm,min_u_turn_width_mm,min_edge_from_wall_mm,max_step_height_mm,slope_angle_auto_deg,sensor_distance_m,sensor_degree_deg,ip_rating,hepa,min_operating_temp_c,max_operating_temp_c,min_operating_humidity_pct,max_operating_humidity_pct,application,outdoor,indoor,fn_sweep_no_vacuum,fn_sweep_vacuum,fn_mop_dry,fn_mop_wet,fn_scrub_brush_roller,fn_scrub_brush_disc,nav_2d_lidar,nav_3d_lidar,nav_vslam,sensor_rgb,sensor_rgbd,sensor_ultrasonic,anti_collision,anti_drop,spot_ai,manual_drive,multi_robot_connect,auto_task_switch,iot_integration,work_station,dock_charge,manual_charge,floor_layout_method,floor_rough_surface,floor_smooth_surface,floor_real_wood,floor_paving_blocks,floor_granite_tiles,floor_ceramic_tiles,floor_marble,floor_terrazzo,floor_nature_stone,floor_terracotta,floor_smooth_concrete,floor_coarse_concrete,floor_stamped_concrete,floor_epoxy,floor_pu,floor_asphalt,floor_short_carpet,floor_long_carpet,floor_spc,floor_wpc,floor_laminate,floor_vinyl_pvc,floor_washed_sand)
SELECT r.id,1250,820,1150,220,840,600,760,50,NULL,NULL,20,NULL,70,1.4,1.4,4234,4234,3024,3024,NULL,80,70,10,NULL,FALSE,TRUE,NULL,NULL,'Lithium-Ion Polymer',24,120,2,8,4,10,900,1280,20,NULL,NULL,1300,NULL,20,10,NULL,NULL,'IPX3',NULL,NULL,NULL,NULL,NULL,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,TRUE,TRUE,FALSE
FROM robots r
WHERE lower(r.brand) = lower('Gausium') AND lower(r.model) = lower('Marvel')
  AND NOT EXISTS (SELECT 1 FROM robot_specs_cleaning s WHERE s.robot_id = r.id);

-- ── Gausium Omnie Disc Brush ─────────────────────────────────────────────
INSERT INTO robots (brand, model, robot_type, test_status)
SELECT 'Gausium', 'Omnie Disc Brush', 'CLEANING', 'DRAFT'
WHERE NOT EXISTS (SELECT 1 FROM robots
                  WHERE lower(brand) = lower('Gausium') AND lower(model) = lower('Omnie Disc Brush'));

INSERT INTO robot_specs_cleaning (robot_id,dimension_l_mm,dimension_w_mm,dimension_h_mm,robot_weight_kg,sweep_width_mm,scrub_width_mm,mop_width_mm,brush_pressure_kg,roller_speed_rpm,brush_speed_rpm,vacuum_pressure_kpa,vibration_more_than,noise_level_db,max_travelling_speed_ms,max_operation_speed_ms,sweep_efficiency_sqm_h,scrub_efficiency_sqm_h,mop_efficiency_sqm_h,sweep_scrub_efficiency_sqm_h,vacuum_efficiency_sqm_h,cleaning_capacity_l,waste_capacity_l,trash_capacity_l,dust_bag_capacity_l,dust_bag_charging_dock,auto_clean,max_output_power_w,drive_motor_power_w,battery_type,battery_voltage_v,battery_capacity_ah,battery_charging_time_hr,sweep_work_time_hr,scrub_work_time_hr,mop_work_time_hr,min_pass_width_mm,min_pass_height_mm,max_vertical_obstacle_height_mm,max_trench_clearance_mm,max_narrow_mm,min_u_turn_width_mm,min_edge_from_wall_mm,max_step_height_mm,slope_angle_auto_deg,sensor_distance_m,sensor_degree_deg,ip_rating,hepa,min_operating_temp_c,max_operating_temp_c,min_operating_humidity_pct,max_operating_humidity_pct,application,outdoor,indoor,fn_sweep_no_vacuum,fn_sweep_vacuum,fn_mop_dry,fn_mop_wet,fn_scrub_brush_roller,fn_scrub_brush_disc,nav_2d_lidar,nav_3d_lidar,nav_vslam,sensor_rgb,sensor_rgbd,sensor_ultrasonic,anti_collision,anti_drop,spot_ai,manual_drive,multi_robot_connect,auto_task_switch,iot_integration,work_station,dock_charge,manual_charge,floor_layout_method,floor_rough_surface,floor_smooth_surface,floor_real_wood,floor_paving_blocks,floor_granite_tiles,floor_ceramic_tiles,floor_marble,floor_terrazzo,floor_nature_stone,floor_terracotta,floor_smooth_concrete,floor_coarse_concrete,floor_stamped_concrete,floor_epoxy,floor_pu,floor_asphalt,floor_short_carpet,floor_long_carpet,floor_spc,floor_wpc,floor_laminate,floor_vinyl_pvc,floor_washed_sand)
SELECT r.id,810,700,1070,157,NULL,520,715,25,NULL,240,NULL,NULL,70,1.4,1.4,NULL,2621,3604,NULL,NULL,33,24,1.2,NULL,FALSE,FALSE,NULL,NULL,'Lithium Iron Phosphate',24,60,2,8,3,8,800,1100,15,NULL,NULL,1100,NULL,15,4.5999999999999996,100,360,'IPX3',NULL,NULL,NULL,NULL,NULL,TRUE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,FALSE
FROM robots r
WHERE lower(r.brand) = lower('Gausium') AND lower(r.model) = lower('Omnie Disc Brush')
  AND NOT EXISTS (SELECT 1 FROM robot_specs_cleaning s WHERE s.robot_id = r.id);

-- ── Gausium Omnie Roller Brush ─────────────────────────────────────────────
INSERT INTO robots (brand, model, robot_type, test_status)
SELECT 'Gausium', 'Omnie Roller Brush', 'CLEANING', 'DRAFT'
WHERE NOT EXISTS (SELECT 1 FROM robots
                  WHERE lower(brand) = lower('Gausium') AND lower(model) = lower('Omnie Roller Brush'));

INSERT INTO robot_specs_cleaning (robot_id,dimension_l_mm,dimension_w_mm,dimension_h_mm,robot_weight_kg,sweep_width_mm,scrub_width_mm,mop_width_mm,brush_pressure_kg,roller_speed_rpm,brush_speed_rpm,vacuum_pressure_kpa,vibration_more_than,noise_level_db,max_travelling_speed_ms,max_operation_speed_ms,sweep_efficiency_sqm_h,scrub_efficiency_sqm_h,mop_efficiency_sqm_h,sweep_scrub_efficiency_sqm_h,vacuum_efficiency_sqm_h,cleaning_capacity_l,waste_capacity_l,trash_capacity_l,dust_bag_capacity_l,dust_bag_charging_dock,auto_clean,max_output_power_w,drive_motor_power_w,battery_type,battery_voltage_v,battery_capacity_ah,battery_charging_time_hr,sweep_work_time_hr,scrub_work_time_hr,mop_work_time_hr,min_pass_width_mm,min_pass_height_mm,max_vertical_obstacle_height_mm,max_trench_clearance_mm,max_narrow_mm,min_u_turn_width_mm,min_edge_from_wall_mm,max_step_height_mm,slope_angle_auto_deg,sensor_distance_m,sensor_degree_deg,ip_rating,hepa,min_operating_temp_c,max_operating_temp_c,min_operating_humidity_pct,max_operating_humidity_pct,application,outdoor,indoor,fn_sweep_no_vacuum,fn_sweep_vacuum,fn_mop_dry,fn_mop_wet,fn_scrub_brush_roller,fn_scrub_brush_disc,nav_2d_lidar,nav_3d_lidar,nav_vslam,sensor_rgb,sensor_rgbd,sensor_ultrasonic,anti_collision,anti_drop,spot_ai,manual_drive,multi_robot_connect,auto_task_switch,iot_integration,work_station,dock_charge,manual_charge,floor_layout_method,floor_rough_surface,floor_smooth_surface,floor_real_wood,floor_paving_blocks,floor_granite_tiles,floor_ceramic_tiles,floor_marble,floor_terrazzo,floor_nature_stone,floor_terracotta,floor_smooth_concrete,floor_coarse_concrete,floor_stamped_concrete,floor_epoxy,floor_pu,floor_asphalt,floor_short_carpet,floor_long_carpet,floor_spc,floor_wpc,floor_laminate,floor_vinyl_pvc,floor_washed_sand)
SELECT r.id,810,700,1070,148,780,406,715,25,1000,1000,NULL,NULL,70,1.4,1.4,3931,2046,3604,NULL,NULL,33,24,1.2,NULL,FALSE,FALSE,NULL,NULL,'Lithium Iron Phosphate',24,60,2,8,3,8,800,1100,15,NULL,NULL,1100,NULL,15,4.5999999999999996,100,360,'IPX3',NULL,NULL,NULL,NULL,NULL,TRUE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE
FROM robots r
WHERE lower(r.brand) = lower('Gausium') AND lower(r.model) = lower('Omnie Roller Brush')
  AND NOT EXISTS (SELECT 1 FROM robot_specs_cleaning s WHERE s.robot_id = r.id);

-- ── Gausium Scrubber 50 Pro (M50)Roller Brush ─────────────────────────────────────────────
INSERT INTO robots (brand, model, robot_type, test_status)
SELECT 'Gausium', 'Scrubber 50 Pro (M50)Roller Brush', 'CLEANING', 'DRAFT'
WHERE NOT EXISTS (SELECT 1 FROM robots
                  WHERE lower(brand) = lower('Gausium') AND lower(model) = lower('Scrubber 50 Pro (M50)Roller Brush'));

INSERT INTO robot_specs_cleaning (robot_id,dimension_l_mm,dimension_w_mm,dimension_h_mm,robot_weight_kg,sweep_width_mm,scrub_width_mm,mop_width_mm,brush_pressure_kg,roller_speed_rpm,brush_speed_rpm,vacuum_pressure_kpa,vibration_more_than,noise_level_db,max_travelling_speed_ms,max_operation_speed_ms,sweep_efficiency_sqm_h,scrub_efficiency_sqm_h,mop_efficiency_sqm_h,sweep_scrub_efficiency_sqm_h,vacuum_efficiency_sqm_h,cleaning_capacity_l,waste_capacity_l,trash_capacity_l,dust_bag_capacity_l,dust_bag_charging_dock,auto_clean,max_output_power_w,drive_motor_power_w,battery_type,battery_voltage_v,battery_capacity_ah,battery_charging_time_hr,sweep_work_time_hr,scrub_work_time_hr,mop_work_time_hr,min_pass_width_mm,min_pass_height_mm,max_vertical_obstacle_height_mm,max_trench_clearance_mm,max_narrow_mm,min_u_turn_width_mm,min_edge_from_wall_mm,max_step_height_mm,slope_angle_auto_deg,sensor_distance_m,sensor_degree_deg,ip_rating,hepa,min_operating_temp_c,max_operating_temp_c,min_operating_humidity_pct,max_operating_humidity_pct,application,outdoor,indoor,fn_sweep_no_vacuum,fn_sweep_vacuum,fn_mop_dry,fn_mop_wet,fn_scrub_brush_roller,fn_scrub_brush_disc,nav_2d_lidar,nav_3d_lidar,nav_vslam,sensor_rgb,sensor_rgbd,sensor_ultrasonic,anti_collision,anti_drop,spot_ai,manual_drive,multi_robot_connect,auto_task_switch,iot_integration,work_station,dock_charge,manual_charge,floor_layout_method,floor_rough_surface,floor_smooth_surface,floor_real_wood,floor_paving_blocks,floor_granite_tiles,floor_ceramic_tiles,floor_marble,floor_terrazzo,floor_nature_stone,floor_terracotta,floor_smooth_concrete,floor_coarse_concrete,floor_stamped_concrete,floor_epoxy,floor_pu,floor_asphalt,floor_short_carpet,floor_long_carpet,floor_spc,floor_wpc,floor_laminate,floor_vinyl_pvc,floor_washed_sand)
SELECT r.id,860,700,1030,140,780,460,NULL,18,270,1000,18,2.5,82,0.9,0.9,900,1921,NULL,NULL,NULL,30,24,1.2,NULL,FALSE,FALSE,1200,300,'Lithium-Ion Polymer',24,60,2,NULL,6,NULL,900,NULL,NULL,NULL,NULL,1200,0,NULL,4.5999999999999996,NULL,360,'IPX3','H13',0,45,20,75,TRUE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,FALSE
FROM robots r
WHERE lower(r.brand) = lower('Gausium') AND lower(r.model) = lower('Scrubber 50 Pro (M50)Roller Brush')
  AND NOT EXISTS (SELECT 1 FROM robot_specs_cleaning s WHERE s.robot_id = r.id);

-- ── Gausium Scrubber 50 Pro (M50)Disc Brush ─────────────────────────────────────────────
INSERT INTO robots (brand, model, robot_type, test_status)
SELECT 'Gausium', 'Scrubber 50 Pro (M50)Disc Brush', 'CLEANING', 'DRAFT'
WHERE NOT EXISTS (SELECT 1 FROM robots
                  WHERE lower(brand) = lower('Gausium') AND lower(model) = lower('Scrubber 50 Pro (M50)Disc Brush'));

INSERT INTO robot_specs_cleaning (robot_id,dimension_l_mm,dimension_w_mm,dimension_h_mm,robot_weight_kg,sweep_width_mm,scrub_width_mm,mop_width_mm,brush_pressure_kg,roller_speed_rpm,brush_speed_rpm,vacuum_pressure_kpa,vibration_more_than,noise_level_db,max_travelling_speed_ms,max_operation_speed_ms,sweep_efficiency_sqm_h,scrub_efficiency_sqm_h,mop_efficiency_sqm_h,sweep_scrub_efficiency_sqm_h,vacuum_efficiency_sqm_h,cleaning_capacity_l,waste_capacity_l,trash_capacity_l,dust_bag_capacity_l,dust_bag_charging_dock,auto_clean,max_output_power_w,drive_motor_power_w,battery_type,battery_voltage_v,battery_capacity_ah,battery_charging_time_hr,sweep_work_time_hr,scrub_work_time_hr,mop_work_time_hr,min_pass_width_mm,min_pass_height_mm,max_vertical_obstacle_height_mm,max_trench_clearance_mm,max_narrow_mm,min_u_turn_width_mm,min_edge_from_wall_mm,max_step_height_mm,slope_angle_auto_deg,sensor_distance_m,sensor_degree_deg,ip_rating,hepa,min_operating_temp_c,max_operating_temp_c,min_operating_humidity_pct,max_operating_humidity_pct,application,outdoor,indoor,fn_sweep_no_vacuum,fn_sweep_vacuum,fn_mop_dry,fn_mop_wet,fn_scrub_brush_roller,fn_scrub_brush_disc,nav_2d_lidar,nav_3d_lidar,nav_vslam,sensor_rgb,sensor_rgbd,sensor_ultrasonic,anti_collision,anti_drop,spot_ai,manual_drive,multi_robot_connect,auto_task_switch,iot_integration,work_station,dock_charge,manual_charge,floor_layout_method,floor_rough_surface,floor_smooth_surface,floor_real_wood,floor_paving_blocks,floor_granite_tiles,floor_ceramic_tiles,floor_marble,floor_terrazzo,floor_nature_stone,floor_terracotta,floor_smooth_concrete,floor_coarse_concrete,floor_stamped_concrete,floor_epoxy,floor_pu,floor_asphalt,floor_short_carpet,floor_long_carpet,floor_spc,floor_wpc,floor_laminate,floor_vinyl_pvc,floor_washed_sand)
SELECT r.id,860,700,1030,150,0,500,NULL,25,270,1000,18,2.5,82,0.9,0.9,900,1490,NULL,NULL,NULL,30,24,1.2,NULL,FALSE,FALSE,1200,300,'Lithium-Ion Polymer',24,60,2,NULL,8,NULL,900,NULL,NULL,NULL,NULL,1200,40,NULL,4.5999999999999996,NULL,NULL,'IPX3','H13',0,45,20,75,TRUE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,FALSE
FROM robots r
WHERE lower(r.brand) = lower('Gausium') AND lower(r.model) = lower('Scrubber 50 Pro (M50)Disc Brush')
  AND NOT EXISTS (SELECT 1 FROM robot_specs_cleaning s WHERE s.robot_id = r.id);

-- ── Gausium Ecobot Vacuum 40 (M40) ─────────────────────────────────────────────
INSERT INTO robots (brand, model, robot_type, test_status)
SELECT 'Gausium', 'Ecobot Vacuum 40 (M40)', 'CLEANING', 'DRAFT'
WHERE NOT EXISTS (SELECT 1 FROM robots
                  WHERE lower(brand) = lower('Gausium') AND lower(model) = lower('Ecobot Vacuum 40 (M40)'));

INSERT INTO robot_specs_cleaning (robot_id,dimension_l_mm,dimension_w_mm,dimension_h_mm,robot_weight_kg,sweep_width_mm,scrub_width_mm,mop_width_mm,brush_pressure_kg,roller_speed_rpm,brush_speed_rpm,vacuum_pressure_kpa,vibration_more_than,noise_level_db,max_travelling_speed_ms,max_operation_speed_ms,sweep_efficiency_sqm_h,scrub_efficiency_sqm_h,mop_efficiency_sqm_h,sweep_scrub_efficiency_sqm_h,vacuum_efficiency_sqm_h,cleaning_capacity_l,waste_capacity_l,trash_capacity_l,dust_bag_capacity_l,dust_bag_charging_dock,auto_clean,max_output_power_w,drive_motor_power_w,battery_type,battery_voltage_v,battery_capacity_ah,battery_charging_time_hr,sweep_work_time_hr,scrub_work_time_hr,mop_work_time_hr,min_pass_width_mm,min_pass_height_mm,max_vertical_obstacle_height_mm,max_trench_clearance_mm,max_narrow_mm,min_u_turn_width_mm,min_edge_from_wall_mm,max_step_height_mm,slope_angle_auto_deg,sensor_distance_m,sensor_degree_deg,ip_rating,hepa,min_operating_temp_c,max_operating_temp_c,min_operating_humidity_pct,max_operating_humidity_pct,application,outdoor,indoor,fn_sweep_no_vacuum,fn_sweep_vacuum,fn_mop_dry,fn_mop_wet,fn_scrub_brush_roller,fn_scrub_brush_disc,nav_2d_lidar,nav_3d_lidar,nav_vslam,sensor_rgb,sensor_rgbd,sensor_ultrasonic,anti_collision,anti_drop,spot_ai,manual_drive,multi_robot_connect,auto_task_switch,iot_integration,work_station,dock_charge,manual_charge,floor_layout_method,floor_rough_surface,floor_smooth_surface,floor_real_wood,floor_paving_blocks,floor_granite_tiles,floor_ceramic_tiles,floor_marble,floor_terrazzo,floor_nature_stone,floor_terracotta,floor_smooth_concrete,floor_coarse_concrete,floor_stamped_concrete,floor_epoxy,floor_pu,floor_asphalt,floor_short_carpet,floor_long_carpet,floor_spc,floor_wpc,floor_laminate,floor_vinyl_pvc,floor_washed_sand)
SELECT r.id,790,730,900,93,720,NULL,NULL,NULL,NULL,NULL,24,2.5,70,1,1,1200,NULL,NULL,NULL,1200,NULL,NULL,2.5,12,FALSE,FALSE,1000,300,'Lithium Iron Phosphate',24,60,2,3,NULL,18,800,NULL,20,35,870,1100,0,NULL,4,25,NULL,'IPX3','H13',0,45,10,75,TRUE,FALSE,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,TRUE,TRUE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,FALSE
FROM robots r
WHERE lower(r.brand) = lower('Gausium') AND lower(r.model) = lower('Ecobot Vacuum 40 (M40)')
  AND NOT EXISTS (SELECT 1 FROM robot_specs_cleaning s WHERE s.robot_id = r.id);

-- ── Gausium Ecobot Scrub 75 (M75) ─────────────────────────────────────────────
INSERT INTO robots (brand, model, robot_type, test_status)
SELECT 'Gausium', 'Ecobot Scrub 75 (M75)', 'CLEANING', 'DRAFT'
WHERE NOT EXISTS (SELECT 1 FROM robots
                  WHERE lower(brand) = lower('Gausium') AND lower(model) = lower('Ecobot Scrub 75 (M75)'));

INSERT INTO robot_specs_cleaning (robot_id,dimension_l_mm,dimension_w_mm,dimension_h_mm,robot_weight_kg,sweep_width_mm,scrub_width_mm,mop_width_mm,brush_pressure_kg,roller_speed_rpm,brush_speed_rpm,vacuum_pressure_kpa,vibration_more_than,noise_level_db,max_travelling_speed_ms,max_operation_speed_ms,sweep_efficiency_sqm_h,scrub_efficiency_sqm_h,mop_efficiency_sqm_h,sweep_scrub_efficiency_sqm_h,vacuum_efficiency_sqm_h,cleaning_capacity_l,waste_capacity_l,trash_capacity_l,dust_bag_capacity_l,dust_bag_charging_dock,auto_clean,max_output_power_w,drive_motor_power_w,battery_type,battery_voltage_v,battery_capacity_ah,battery_charging_time_hr,sweep_work_time_hr,scrub_work_time_hr,mop_work_time_hr,min_pass_width_mm,min_pass_height_mm,max_vertical_obstacle_height_mm,max_trench_clearance_mm,max_narrow_mm,min_u_turn_width_mm,min_edge_from_wall_mm,max_step_height_mm,slope_angle_auto_deg,sensor_distance_m,sensor_degree_deg,ip_rating,hepa,min_operating_temp_c,max_operating_temp_c,min_operating_humidity_pct,max_operating_humidity_pct,application,outdoor,indoor,fn_sweep_no_vacuum,fn_sweep_vacuum,fn_mop_dry,fn_mop_wet,fn_scrub_brush_roller,fn_scrub_brush_disc,nav_2d_lidar,nav_3d_lidar,nav_vslam,sensor_rgb,sensor_rgbd,sensor_ultrasonic,anti_collision,anti_drop,spot_ai,manual_drive,multi_robot_connect,auto_task_switch,iot_integration,work_station,dock_charge,manual_charge,floor_layout_method,floor_rough_surface,floor_smooth_surface,floor_real_wood,floor_paving_blocks,floor_granite_tiles,floor_ceramic_tiles,floor_marble,floor_terrazzo,floor_nature_stone,floor_terracotta,floor_smooth_concrete,floor_coarse_concrete,floor_stamped_concrete,floor_epoxy,floor_pu,floor_asphalt,floor_short_carpet,floor_long_carpet,floor_spc,floor_wpc,floor_laminate,floor_vinyl_pvc,floor_washed_sand)
SELECT r.id,1370,962,1417,400,690,750,NULL,45,NULL,NULL,15,NULL,75,1.1599999999999999,1.1599999999999999,NULL,3000,NULL,NULL,NULL,75,50,1.2,NULL,FALSE,FALSE,NULL,NULL,'Lithium Iron Phosphate',24,240,5,5,5,NULL,1400,NULL,NULL,NULL,NULL,2000,200,NULL,3,150,NULL,'IPX3',NULL,NULL,NULL,NULL,NULL,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,NULL,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE
FROM robots r
WHERE lower(r.brand) = lower('Gausium') AND lower(r.model) = lower('Ecobot Scrub 75 (M75)')
  AND NOT EXISTS (SELECT 1 FROM robot_specs_cleaning s WHERE s.robot_id = r.id);

-- ── Gausium Ecobot Scrubber 75 ─────────────────────────────────────────────
INSERT INTO robots (brand, model, robot_type, test_status)
SELECT 'Gausium', 'Ecobot Scrubber 75', 'CLEANING', 'DRAFT'
WHERE NOT EXISTS (SELECT 1 FROM robots
                  WHERE lower(brand) = lower('Gausium') AND lower(model) = lower('Ecobot Scrubber 75'));

INSERT INTO robot_specs_cleaning (robot_id,dimension_l_mm,dimension_w_mm,dimension_h_mm,robot_weight_kg,sweep_width_mm,scrub_width_mm,mop_width_mm,brush_pressure_kg,roller_speed_rpm,brush_speed_rpm,vacuum_pressure_kpa,vibration_more_than,noise_level_db,max_travelling_speed_ms,max_operation_speed_ms,sweep_efficiency_sqm_h,scrub_efficiency_sqm_h,mop_efficiency_sqm_h,sweep_scrub_efficiency_sqm_h,vacuum_efficiency_sqm_h,cleaning_capacity_l,waste_capacity_l,trash_capacity_l,dust_bag_capacity_l,dust_bag_charging_dock,auto_clean,max_output_power_w,drive_motor_power_w,battery_type,battery_voltage_v,battery_capacity_ah,battery_charging_time_hr,sweep_work_time_hr,scrub_work_time_hr,mop_work_time_hr,min_pass_width_mm,min_pass_height_mm,max_vertical_obstacle_height_mm,max_trench_clearance_mm,max_narrow_mm,min_u_turn_width_mm,min_edge_from_wall_mm,max_step_height_mm,slope_angle_auto_deg,sensor_distance_m,sensor_degree_deg,ip_rating,hepa,min_operating_temp_c,max_operating_temp_c,min_operating_humidity_pct,max_operating_humidity_pct,application,outdoor,indoor,fn_sweep_no_vacuum,fn_sweep_vacuum,fn_mop_dry,fn_mop_wet,fn_scrub_brush_roller,fn_scrub_brush_disc,nav_2d_lidar,nav_3d_lidar,nav_vslam,sensor_rgb,sensor_rgbd,sensor_ultrasonic,anti_collision,anti_drop,spot_ai,manual_drive,multi_robot_connect,auto_task_switch,iot_integration,work_station,dock_charge,manual_charge,floor_layout_method,floor_rough_surface,floor_smooth_surface,floor_real_wood,floor_paving_blocks,floor_granite_tiles,floor_ceramic_tiles,floor_marble,floor_terrazzo,floor_nature_stone,floor_terracotta,floor_smooth_concrete,floor_coarse_concrete,floor_stamped_concrete,floor_epoxy,floor_pu,floor_asphalt,floor_short_carpet,floor_long_carpet,floor_spc,floor_wpc,floor_laminate,floor_vinyl_pvc,floor_washed_sand)
SELECT r.id,1370,962,1417,400,690,750,NULL,45,NULL,NULL,15,NULL,75,1.1599999999999999,1.1599999999999999,1050,3000,NULL,NULL,NULL,75,50,1.3,NULL,FALSE,FALSE,NULL,NULL,'Lithium Iron Phosphate',24,240,5,5,5,NULL,1400,NULL,10,NULL,NULL,2000,200,NULL,3,150,NULL,'IPX3',NULL,NULL,NULL,NULL,NULL,TRUE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE
FROM robots r
WHERE lower(r.brand) = lower('Gausium') AND lower(r.model) = lower('Ecobot Scrubber 75')
  AND NOT EXISTS (SELECT 1 FROM robot_specs_cleaning s WHERE s.robot_id = r.id);

-- ── Gausium Phantas v1.1 ─────────────────────────────────────────────
INSERT INTO robots (brand, model, robot_type, test_status)
SELECT 'Gausium', 'Phantas v1.1', 'CLEANING', 'DRAFT'
WHERE NOT EXISTS (SELECT 1 FROM robots
                  WHERE lower(brand) = lower('Gausium') AND lower(model) = lower('Phantas v1.1'));

INSERT INTO robot_specs_cleaning (robot_id,dimension_l_mm,dimension_w_mm,dimension_h_mm,robot_weight_kg,sweep_width_mm,scrub_width_mm,mop_width_mm,brush_pressure_kg,roller_speed_rpm,brush_speed_rpm,vacuum_pressure_kpa,vibration_more_than,noise_level_db,max_travelling_speed_ms,max_operation_speed_ms,sweep_efficiency_sqm_h,scrub_efficiency_sqm_h,mop_efficiency_sqm_h,sweep_scrub_efficiency_sqm_h,vacuum_efficiency_sqm_h,cleaning_capacity_l,waste_capacity_l,trash_capacity_l,dust_bag_capacity_l,dust_bag_charging_dock,auto_clean,max_output_power_w,drive_motor_power_w,battery_type,battery_voltage_v,battery_capacity_ah,battery_charging_time_hr,sweep_work_time_hr,scrub_work_time_hr,mop_work_time_hr,min_pass_width_mm,min_pass_height_mm,max_vertical_obstacle_height_mm,max_trench_clearance_mm,max_narrow_mm,min_u_turn_width_mm,min_edge_from_wall_mm,max_step_height_mm,slope_angle_auto_deg,sensor_distance_m,sensor_degree_deg,ip_rating,hepa,min_operating_temp_c,max_operating_temp_c,min_operating_humidity_pct,max_operating_humidity_pct,application,outdoor,indoor,fn_sweep_no_vacuum,fn_sweep_vacuum,fn_mop_dry,fn_mop_wet,fn_scrub_brush_roller,fn_scrub_brush_disc,nav_2d_lidar,nav_3d_lidar,nav_vslam,sensor_rgb,sensor_rgbd,sensor_ultrasonic,anti_collision,anti_drop,spot_ai,manual_drive,multi_robot_connect,auto_task_switch,iot_integration,work_station,dock_charge,manual_charge,floor_layout_method,floor_rough_surface,floor_smooth_surface,floor_real_wood,floor_paving_blocks,floor_granite_tiles,floor_ceramic_tiles,floor_marble,floor_terrazzo,floor_nature_stone,floor_terracotta,floor_smooth_concrete,floor_coarse_concrete,floor_stamped_concrete,floor_epoxy,floor_pu,floor_asphalt,floor_short_carpet,floor_long_carpet,floor_spc,floor_wpc,floor_laminate,floor_vinyl_pvc,floor_washed_sand)
SELECT r.id,540,440,617,48,410,330,NULL,NULL,NULL,NULL,NULL,NULL,65,0.8,0.8,450,450,950,NULL,950,11.5,10.5,0.7,8,FALSE,FALSE,NULL,NULL,'Lithium Iron Phosphate',24,40,2,6,4,8,520,650,10,NULL,NULL,620,0,NULL,8,25,NULL,'IPX3',NULL,NULL,NULL,NULL,NULL,TRUE,FALSE,TRUE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,TRUE,FALSE,TRUE,TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,FALSE,TRUE,TRUE,TRUE,FALSE,FALSE
FROM robots r
WHERE lower(r.brand) = lower('Gausium') AND lower(r.model) = lower('Phantas v1.1')
  AND NOT EXISTS (SELECT 1 FROM robot_specs_cleaning s WHERE s.robot_id = r.id);

-- ── Gausium Phantas v1.3 ─────────────────────────────────────────────
INSERT INTO robots (brand, model, robot_type, test_status)
SELECT 'Gausium', 'Phantas v1.3', 'CLEANING', 'DRAFT'
WHERE NOT EXISTS (SELECT 1 FROM robots
                  WHERE lower(brand) = lower('Gausium') AND lower(model) = lower('Phantas v1.3'));

INSERT INTO robot_specs_cleaning (robot_id,dimension_l_mm,dimension_w_mm,dimension_h_mm,robot_weight_kg,sweep_width_mm,scrub_width_mm,mop_width_mm,brush_pressure_kg,roller_speed_rpm,brush_speed_rpm,vacuum_pressure_kpa,vibration_more_than,noise_level_db,max_travelling_speed_ms,max_operation_speed_ms,sweep_efficiency_sqm_h,scrub_efficiency_sqm_h,mop_efficiency_sqm_h,sweep_scrub_efficiency_sqm_h,vacuum_efficiency_sqm_h,cleaning_capacity_l,waste_capacity_l,trash_capacity_l,dust_bag_capacity_l,dust_bag_charging_dock,auto_clean,max_output_power_w,drive_motor_power_w,battery_type,battery_voltage_v,battery_capacity_ah,battery_charging_time_hr,sweep_work_time_hr,scrub_work_time_hr,mop_work_time_hr,min_pass_width_mm,min_pass_height_mm,max_vertical_obstacle_height_mm,max_trench_clearance_mm,max_narrow_mm,min_u_turn_width_mm,min_edge_from_wall_mm,max_step_height_mm,slope_angle_auto_deg,sensor_distance_m,sensor_degree_deg,ip_rating,hepa,min_operating_temp_c,max_operating_temp_c,min_operating_humidity_pct,max_operating_humidity_pct,application,outdoor,indoor,fn_sweep_no_vacuum,fn_sweep_vacuum,fn_mop_dry,fn_mop_wet,fn_scrub_brush_roller,fn_scrub_brush_disc,nav_2d_lidar,nav_3d_lidar,nav_vslam,sensor_rgb,sensor_rgbd,sensor_ultrasonic,anti_collision,anti_drop,spot_ai,manual_drive,multi_robot_connect,auto_task_switch,iot_integration,work_station,dock_charge,manual_charge,floor_layout_method,floor_rough_surface,floor_smooth_surface,floor_real_wood,floor_paving_blocks,floor_granite_tiles,floor_ceramic_tiles,floor_marble,floor_terrazzo,floor_nature_stone,floor_terracotta,floor_smooth_concrete,floor_coarse_concrete,floor_stamped_concrete,floor_epoxy,floor_pu,floor_asphalt,floor_short_carpet,floor_long_carpet,floor_spc,floor_wpc,floor_laminate,floor_vinyl_pvc,floor_washed_sand)
SELECT r.id,585,445,619,65,465,330,330,10,NULL,NULL,NULL,NULL,60,0.8,0.8,525,1188,1188,NULL,1674,11.5,10.5,1,6,FALSE,FALSE,NULL,NULL,'Lithium Iron Phosphate',24,40,2,6,4.5,10,650,650,20,NULL,NULL,750,0,NULL,8,25,NULL,'IPX3',NULL,NULL,NULL,NULL,NULL,TRUE,FALSE,TRUE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,FALSE,TRUE,FALSE,TRUE,TRUE,TRUE,FALSE,FALSE
FROM robots r
WHERE lower(r.brand) = lower('Gausium') AND lower(r.model) = lower('Phantas v1.3')
  AND NOT EXISTS (SELECT 1 FROM robot_specs_cleaning s WHERE s.robot_id = r.id);

COMMIT;
