package com.raaspal.robotrecommendation.pm.entity;

import jakarta.persistence.*;
import lombok.*;
import org.springframework.data.domain.Persistable;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * One execution of the monday PM sync, kept so a wrong number on the planner can
 * be traced to the import that produced it.
 *
 * <p>The counts matter more than they look: a sudden drop in {@code visitsRead}
 * is how a broken cursor or a renamed column announces itself, and without a
 * recorded history that shows up only as a grid that quietly went sparse.
 */
@Entity
@Table(name = "pm_sync_run")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PmSyncRun implements Persistable<UUID> {

    @Id
    private UUID id;

    @Column(name = "source_board_id", length = 32)
    private String sourceBoardId;

    @Enumerated(EnumType.STRING)
    @Column(name = "service_line", length = 16)
    private PmServiceLine serviceLine;

    /** RUNNING | SUCCESS | FAILED. */
    @Column(name = "status", nullable = false, length = 16)
    private String status;

    /** "scheduler" or the email of whoever pressed sync. */
    @Column(name = "triggered_by", length = 255)
    private String triggeredBy;

    @Column(name = "started_at", nullable = false)
    private OffsetDateTime startedAt;

    @Column(name = "finished_at")
    private OffsetDateTime finishedAt;

    @Column(name = "contracts_read")
    private Integer contractsRead;

    @Column(name = "visits_read")
    private Integer visitsRead;

    @Column(name = "contracts_written")
    private Integer contractsWritten;

    @Column(name = "visits_written")
    private Integer visitsWritten;

    @Column(name = "marked_absent")
    private Integer markedAbsent;

    @Column(name = "error_message", columnDefinition = "TEXT")
    private String errorMessage;

    /**
     * Whether this row still has to be INSERTed.
     *
     * <p>Ids are assigned by the mapper rather than generated by the database,
     * because a visit has to reference its contract's id before either is flushed.
     * Spring Data's default rule is "id is null, therefore new", which with an
     * assigned id would make every insert arrive as a merge - an extra SELECT per
     * row, and a clash with Hibernate's own unsaved-value detection. Implementing
     * Persistable states it outright instead.
     */
    @Transient
    @Builder.Default
    private boolean newEntity = true;

    @Override
    public boolean isNew() {
        return newEntity;
    }

    /** Anything loaded or just written is, by definition, no longer new. */
    @PostPersist
    @PostLoad
    void markPersisted() {
        this.newEntity = false;
    }
}
