package com.raaspal.robotrecommendation.pm.entity;

import jakarta.persistence.*;
import lombok.*;
import org.springframework.data.domain.Persistable;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * One PM visit - a subitem under a {@link PmContract}.
 *
 * <p>These rows are the point of the whole feature. There are roughly 4,400 of
 * them spread under 511 parent items on two boards, several hundred of them
 * already dated into future years, and no view in monday puts them on one
 * timeline. The 52-week grid is built entirely from {@link #planDate}.
 *
 * <p>{@link #actionDate} (the actual visit) is filled on well under a third of
 * rows, so completion is read from {@link #statusBucket}, never from whether an
 * action date exists.
 */
@Entity
@Table(name = "pm_visit")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PmVisit implements Persistable<UUID> {

    @Id
    private UUID id;

    /**
     * Owning contract. A plain id rather than a {@code @ManyToOne} because the
     * sync writes visits in bulk and the planner queries them by joining
     * explicitly; an association here would add a lazy-load per row.
     */
    @Column(name = "pm_contract_id", nullable = false)
    private UUID pmContractId;

    @Column(name = "source_board_id", nullable = false, length = 32)
    private String sourceBoardId;

    @Column(name = "source_item_id", nullable = false, length = 32)
    private String sourceItemId;

    @Column(name = "visit_name", columnDefinition = "TEXT")
    private String visitName;

    /** The n in "PM4", parsed from the name. Null when the name does not carry one. */
    @Column(name = "pm_sequence")
    private Integer pmSequence;

    /** Planned visit date - monday's "Plan" column, and the spine of both views. */
    @Column(name = "plan_date")
    private LocalDate planDate;

    /** Actual visit date - monday's "Action" column. Sparse. */
    @Column(name = "action_date")
    private LocalDate actionDate;

    /** Free text like "10.00-18.00"; shown as-is, never parsed. */
    @Column(name = "time_text", columnDefinition = "TEXT")
    private String timeText;

    @Column(name = "status_raw", columnDefinition = "TEXT")
    private String statusRaw;

    @Enumerated(EnumType.STRING)
    @Column(name = "status_bucket", nullable = false, length = 16)
    private PmStatusBucket statusBucket;

    /** Assigned engineer(s) from monday's people column, comma-joined. */
    @Column(name = "owner_names", columnDefinition = "TEXT")
    private String ownerNames;

    @Column(name = "raw_columns", columnDefinition = "TEXT")
    private String rawColumns;

    @Column(name = "source_updated_at")
    private OffsetDateTime sourceUpdatedAt;

    @Column(name = "first_seen_at", nullable = false)
    private OffsetDateTime firstSeenAt;

    @Column(name = "last_synced_at", nullable = false)
    private OffsetDateTime lastSyncedAt;

    @Column(name = "is_present", nullable = false)
    private boolean isPresent;

    /**
     * Whether this row still has to be INSERTed.
     *
     * <p>Ids are assigned by the mapper rather than generated by the database,
     * because a visit has to reference its contract's id before either is flushed.
     * Spring Data's default rule is "id is null, therefore new", which with an
     * assigned id would make every insert arrive as a merge - an extra SELECT per
     * row, and a clash with Hibernate's own unsaved-value detection. Implementing
     * Persistable states it outright instead.
     */
    @Transient
    @Builder.Default
    private boolean newEntity = true;

    @Override
    public boolean isNew() {
        return newEntity;
    }

    /** Anything loaded or just written is, by definition, no longer new. */
    @PostPersist
    @PostLoad
    void markPersisted() {
        this.newEntity = false;
    }
}
